version: '2'
services:
  recognition-server:
    image: kasvith/opencv-python2
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python server.py"